### ISSUE TITLE
[discussion] flavors & schemes vs dart file naming vs readme instructions

### ISSUE THREAD

**Issue by JigneshPatel23** [clayelliot/tictic-vgs#4]
Thank you so much for creating and sharing this great template project. 🙏 

This project brings many things to learn and I am on the way..

One thing got my attention and I think it would be better to clear my thoughts/understanding.

**I think these are intentional - maybe because of it's not like a normal dart file and to showcase it's entry-point or just to sync with iOS target naming style(e.g. Runner).**

Everywhere project is using small case with underscore for naming dart files except target file or main entry points.
e.g. main_Development.dart, main_Staging.dart, main_Production.dart

iOS Scheme: Development, Staging, Production
Android flavor: Development, Staging, Production
Dart Target: main_Development.dart, main_Staging.dart, main_Production.dart
README: development, staging, production

I have tried the small case version as mentioned in README and works fine without any issue on my Mac.

**Comment by felangel** [comment]
Hey 👋 
Thanks for bringing this up! It's a bug in the form submission script which should be fixed shortly. The flavor names should be lowercase (`development`, `production`, `staging`, `integration`) and the `main.dart` entrypoints should be: `main_development.dart`, etc.

**Comment by JigneshPatel23** [comment]
Oh understood thanks for clarification. 

Also I found production app name has empty brace [] as suffix for iOS and Android.


For android to run and pick google services json from flavor specific directory I need to update google services plugin version. 
Not sure it's only for me or other people also facing the same.

**Comment by felangel** [comment]
> Okay got it, thanks. 👍🏻
> 
> Also I found production app name has empty brace [] as suffix for iOS and Android.
> 
> For android to run and pick google services json from flavor specific directory I need to update google services plugin version.
> Not sure it's only for me or other people also facing the same.

That is intentional. In production there is no suffix and it should use the google services json from the production flavor directory
