### ISSUE TITLE
ci: few workflows are not triggered as expected

### ISSUE THREAD

**Issue by JigneshPatel23** [clayelliot/tictic-vgs#6]
**Description**

When user changes on authentication repository and submit pull request, we expect to trigger the CI workflow for the same.

Expected workflow(authentication_repository.yaml) is not triggered for this pull request.
e.g. https://github.com/clayelliot/tictic-vgs/pull/5

There is `tictic` (project name) in path on most of the places on github action workflows and due to this it may not find the relevant file/directory structure changes and can't trigger appropriate workflow. 

**Requirements**

- [ ] appropriate CI system workflow should be triggered as expected

**Comment by felangel** [comment]
@JigneshPatel23 sorry for the inconvenience this was fixed as part of https://github.com/VGVentures/very_good_start/pull/401

**Comment by JigneshPatel23** [comment]
@felangel no convenience at all.

My intention was just to provide feedback to improve VGS if not get already from internal or external people and sorry for reopen again as I was not aware team is aware about this or has been already fixed. 

Thanks you so much for your time and submitting PR for those fixes 👍
